export const ROUND_OF_32_MATCHES = [
  {
    matchId: "M73",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "2A", position: 2, group: "A" },
    awaySlot: { type: "direct", label: "2B", position: 2, group: "B" },
    winnerSlot: "W73",
  },
  {
    matchId: "M74",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1E", position: 1, group: "E" },
    awaySlot: {
      type: "thirdCandidate",
      label: "Mejor 3° ABCDF",
      candidateGroups: ["A", "B", "C", "D", "F"],
      matrixColumn: "1E",
    },
    winnerSlot: "W74",
  },
  {
    matchId: "M75",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1F", position: 1, group: "F" },
    awaySlot: { type: "direct", label: "2C", position: 2, group: "C" },
    winnerSlot: "W75",
  },
  {
    matchId: "M76",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1C", position: 1, group: "C" },
    awaySlot: { type: "direct", label: "2F", position: 2, group: "F" },
    winnerSlot: "W76",
  },
  {
    matchId: "M77",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1I", position: 1, group: "I" },
    awaySlot: {
      type: "thirdCandidate",
      label: "Mejor 3° CDFGH",
      candidateGroups: ["C", "D", "F", "G", "H"],
      matrixColumn: "1I",
    },
    winnerSlot: "W77",
  },
  {
    matchId: "M78",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "2E", position: 2, group: "E" },
    awaySlot: { type: "direct", label: "2I", position: 2, group: "I" },
    winnerSlot: "W78",
  },
  {
    matchId: "M79",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1A", position: 1, group: "A" },
    awaySlot: {
      type: "thirdCandidate",
      label: "Mejor 3° CEFHI",
      candidateGroups: ["C", "E", "F", "H", "I"],
      matrixColumn: "1A",
    },
    winnerSlot: "W79",
  },
  {
    matchId: "M80",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1L", position: 1, group: "L" },
    awaySlot: {
      type: "thirdCandidate",
      label: "Mejor 3° EHIJK",
      candidateGroups: ["E", "H", "I", "J", "K"],
      matrixColumn: "1L",
    },
    winnerSlot: "W80",
  },
  {
    matchId: "M81",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1D", position: 1, group: "D" },
    awaySlot: {
      type: "thirdCandidate",
      label: "Mejor 3° BEFIJ",
      candidateGroups: ["B", "E", "F", "I", "J"],
      matrixColumn: "1D",
    },
    winnerSlot: "W81",
  },
  {
    matchId: "M82",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1G", position: 1, group: "G" },
    awaySlot: {
      type: "thirdCandidate",
      label: "Mejor 3° AEHIJ",
      candidateGroups: ["A", "E", "H", "I", "J"],
      matrixColumn: "1G",
    },
    winnerSlot: "W82",
  },
  {
    matchId: "M83",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "2K", position: 2, group: "K" },
    awaySlot: { type: "direct", label: "2L", position: 2, group: "L" },
    winnerSlot: "W83",
  },
  {
    matchId: "M84",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1H", position: 1, group: "H" },
    awaySlot: { type: "direct", label: "2J", position: 2, group: "J" },
    winnerSlot: "W84",
  },
  {
    matchId: "M85",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1B", position: 1, group: "B" },
    awaySlot: {
      type: "thirdCandidate",
      label: "Mejor 3° EFGIJ",
      candidateGroups: ["E", "F", "G", "I", "J"],
      matrixColumn: "1B",
    },
    winnerSlot: "W85",
  },
  {
    matchId: "M86",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1J", position: 1, group: "J" },
    awaySlot: { type: "direct", label: "2H", position: 2, group: "H" },
    winnerSlot: "W86",
  },
  {
    matchId: "M87",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "1K", position: 1, group: "K" },
    awaySlot: {
      type: "thirdCandidate",
      label: "Mejor 3° DEIJL",
      candidateGroups: ["D", "E", "I", "J", "L"],
      matrixColumn: "1K",
    },
    winnerSlot: "W87",
  },
  {
    matchId: "M88",
    round: "roundOf32",
    title: "Dieciseisavos",
    homeSlot: { type: "direct", label: "2D", position: 2, group: "D" },
    awaySlot: { type: "direct", label: "2G", position: 2, group: "G" },
    winnerSlot: "W88",
  },
];

export const ROUND_OF_16_MATCHES = [
  {
    matchId: "M89",
    round: "roundOf16",
    title: "Octavos",
    homeSlot: { type: "winner", label: "W74" },
    awaySlot: { type: "winner", label: "W77" },
    winnerSlot: "W89",
  },
  {
    matchId: "M90",
    round: "roundOf16",
    title: "Octavos",
    homeSlot: { type: "winner", label: "W73" },
    awaySlot: { type: "winner", label: "W75" },
    winnerSlot: "W90",
  },
  {
    matchId: "M91",
    round: "roundOf16",
    title: "Octavos",
    homeSlot: { type: "winner", label: "W76" },
    awaySlot: { type: "winner", label: "W78" },
    winnerSlot: "W91",
  },
  {
    matchId: "M92",
    round: "roundOf16",
    title: "Octavos",
    homeSlot: { type: "winner", label: "W79" },
    awaySlot: { type: "winner", label: "W80" },
    winnerSlot: "W92",
  },
  {
    matchId: "M93",
    round: "roundOf16",
    title: "Octavos",
    homeSlot: { type: "winner", label: "W83" },
    awaySlot: { type: "winner", label: "W84" },
    winnerSlot: "W93",
  },
  {
    matchId: "M94",
    round: "roundOf16",
    title: "Octavos",
    homeSlot: { type: "winner", label: "W81" },
    awaySlot: { type: "winner", label: "W82" },
    winnerSlot: "W94",
  },
  {
    matchId: "M95",
    round: "roundOf16",
    title: "Octavos",
    homeSlot: { type: "winner", label: "W86" },
    awaySlot: { type: "winner", label: "W88" },
    winnerSlot: "W95",
  },
  {
    matchId: "M96",
    round: "roundOf16",
    title: "Octavos",
    homeSlot: { type: "winner", label: "W85" },
    awaySlot: { type: "winner", label: "W87" },
    winnerSlot: "W96",
  },
];

export const QUARTER_FINAL_MATCHES = [
  {
    matchId: "M97",
    round: "quarterFinals",
    title: "Cuartos",
    homeSlot: { type: "winner", label: "W89" },
    awaySlot: { type: "winner", label: "W90" },
    winnerSlot: "W97",
  },
  {
    matchId: "M98",
    round: "quarterFinals",
    title: "Cuartos",
    homeSlot: { type: "winner", label: "W93" },
    awaySlot: { type: "winner", label: "W94" },
    winnerSlot: "W98",
  },
  {
    matchId: "M99",
    round: "quarterFinals",
    title: "Cuartos",
    homeSlot: { type: "winner", label: "W91" },
    awaySlot: { type: "winner", label: "W92" },
    winnerSlot: "W99",
  },
  {
    matchId: "M100",
    round: "quarterFinals",
    title: "Cuartos",
    homeSlot: { type: "winner", label: "W95" },
    awaySlot: { type: "winner", label: "W96" },
    winnerSlot: "W100",
  },
];

export const SEMI_FINAL_MATCHES = [
  {
    matchId: "M101",
    round: "semiFinals",
    title: "Semifinales",
    homeSlot: { type: "winner", label: "W97" },
    awaySlot: { type: "winner", label: "W98" },
    winnerSlot: "W101",
    loserSlot: "L101",
  },
  {
    matchId: "M102",
    round: "semiFinals",
    title: "Semifinales",
    homeSlot: { type: "winner", label: "W99" },
    awaySlot: { type: "winner", label: "W100" },
    winnerSlot: "W102",
    loserSlot: "L102",
  },
];

export const THIRD_PLACE_MATCHES = [
  {
    matchId: "M103",
    round: "thirdPlace",
    title: "Tercer puesto",
    homeSlot: { type: "loser", label: "L101" },
    awaySlot: { type: "loser", label: "L102" },
    winnerSlot: "W103",
  },
];

export const FINAL_MATCHES = [
  {
    matchId: "M104",
    round: "final",
    title: "Final",
    homeSlot: { type: "winner", label: "W101" },
    awaySlot: { type: "winner", label: "W102" },
    winnerSlot: "W104",
  },
];

export const KNOCKOUT_ROUNDS = [
  {
    key: "roundOf32",
    title: "Dieciseisavos",
    matches: ROUND_OF_32_MATCHES,
  },
  {
    key: "roundOf16",
    title: "Octavos",
    matches: ROUND_OF_16_MATCHES,
  },
  {
    key: "quarterFinals",
    title: "Cuartos",
    matches: QUARTER_FINAL_MATCHES,
  },
  {
    key: "semiFinals",
    title: "Semifinales",
    matches: SEMI_FINAL_MATCHES,
  },
  {
    key: "thirdPlace",
    title: "Tercer puesto",
    matches: THIRD_PLACE_MATCHES,
  },
  {
    key: "final",
    title: "Final",
    matches: FINAL_MATCHES,
  },
];